steamos-grub-mkearlyconfig: Always set prefix and root from search
The prefix set by grub-install like (,gpt4) or (,gpt5) cannot be used as
is and leads to the error below:

	---- Entering early config ----
	cmdpath: (hd0,gpt2)/EFI/steamos
	root   : memdisk
	prefix : (memdisk)/boot/grub
	-------------------------------
	---- Leaving early config ----
	root   : memdisk
	prefix : (,gpt4)/boot/grub
	cfg    : (hd0,gpt2)/EFI/steamos/grub.cfg
	------------------------------
	Hit any key to continue...

	(...)

	error: disk `,gpt4' not found.
	error: can't find command `loadfont'.
	error: disk `,gpt4' not found.
	error: disk `,gpt4' not found.
	error: terminal `gfxterm' isn't found.
	error: disk `,gpt4' not found.
	error: can't find command `loadfont'.
	error: can't find command `loadfont'.
	error: can't find command `loadfont'.
	error: can't find command `loadfont'.
	error: disk `,gpt4' not found.

The previous commit 62fb155 (grub: Set the root to grub early config)
has removed the guess for the prefix if it is not set (the guess
stripped the disk part from the hint).

This always sets the prefix and the root from the search for the /var or
/ partition and ignores the prefix given by grub-install.