steamos-readonly: remount / before changing the btrfs ro property
After running steamos-chroot from a different partset the new rootfs
is mounted read-only, so it's not possible to change the btrfs 'ro'
property to make it read-write without remounting it first.

(A)(root@steamdeck ~)# steamos-chroot --partset other
(chroot[B])(B)(root@steamdeck /)# steamos-readonly disable
ERROR: Could not set subvolume flags: Read-only file system

This reverts commit bce94aa3e0778b2c5055e5e6ca7b717f82d57f58

Fixes https://github.com/ValveSoftware/SteamOS/issues/1833